version: '3.8'
services:
  db:
    image: "postgres:latest"
    restart: on-failure
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_DB=area
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - data:/var/lib/postgresql
      - ./backend/resources/database_scheme.sql:/docker-entrypoint-initdb.d/database_scheme.sql
    ports:
      - "5432:5432"
    networks:
      - backend

  server:
    build: backend
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend

  client_mobile:
    build:
      context: frontend/mobile
    volumes:
      - shared_apk:/app/shared_output
    command: >
      sh -c "flutter pub get &&
             flutter build apk --release &&
             cp build/app/outputs/flutter-apk/app-release.apk /app/shared_output/client.apk &&
             echo 'APK copy with success'"
    networks:
      - frontend

  client_web:
    build: frontend/web
    depends_on:
      - server
      - client_mobile
    ports:
      - "8081:80"
    volumes:
      - shared_apk:/usr/share/nginx/html/apk
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  data:
  shared_apk: